twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menuItems:
            /: Home
            /music: Music
            /scenery-group: Scenery Groups
when@test:
    twig:
        strict_variables: true
